import { Fish, Rod, Tackle, Bait, TreasureItem } from '@/types/game';

export const ALL_FISH: Fish[] = [
  // EASY / ENTRY FISH
  {
    id: 'carp',
    name: 'Carpa',
    nameEn: 'Carp',
    behavior: 'smooth',
    difficulty: 15,
    minSize: 15,
    maxSize: 50,
    basePrice: 30,
    location: 'lake',
    color: '#c28544',
    description: 'Um peixe comum de lagoa. Muito dócil e fácil de pescar.',
    flavorText: 'Ideal para iniciantes praticarem a arte da pesca.',
  },
  {
    id: 'sunfish',
    name: 'Peixe-sol',
    nameEn: 'Sunfish',
    behavior: 'mixed',
    difficulty: 30,
    minSize: 5,
    maxSize: 15,
    basePrice: 30,
    location: 'river',
    color: '#f59e0b',
    description: 'Um peixe de rio comum que gosta de sol quente.',
    flavorText: 'Nada tranquilamente nas águas rasas do rio.',
  },
  {
    id: 'sardine',
    name: 'Sardinha',
    nameEn: 'Sardine',
    behavior: 'dart',
    difficulty: 30,
    minSize: 1,
    maxSize: 12,
    basePrice: 40,
    location: 'ocean',
    color: '#60a5fa',
    description: 'Um peixe oceânico comum que viaja em grandes cardumes.',
    flavorText: 'Muito rápida e saltitante na água salgada.',
  },
  {
    id: 'smallmouth_bass',
    name: 'Robalo Pequeno',
    nameEn: 'Smallmouth Bass',
    behavior: 'mixed',
    difficulty: 28,
    minSize: 12,
    maxSize: 24,
    basePrice: 50,
    location: 'river',
    color: '#84cc16',
    description: 'Um peixe de água doce comum com listras escuras.',
    flavorText: 'Gosta de águas correntes e frescas.',
  },

  // MEDIUM DIFFICULTY
  {
    id: 'largemouth_bass',
    name: 'Robalo Grande',
    nameEn: 'Largemouth Bass',
    behavior: 'mixed',
    difficulty: 50,
    minSize: 18,
    maxSize: 32,
    basePrice: 100,
    location: 'lake',
    color: '#15803d',
    description: 'Um peixe popular de água doce que vive em lagos profundos.',
    flavorText: 'Famoso pelo seu tamanho e sabor suculento.',
  },
  {
    id: 'rainbow_trout',
    name: 'Truta Arco-íris',
    nameEn: 'Rainbow Trout',
    behavior: 'mixed',
    difficulty: 45,
    minSize: 10,
    maxSize: 26,
    basePrice: 65,
    location: 'river',
    color: '#ec4899',
    description: 'Uma truta de água doce com escamas brilhantes multicoloridas.',
    flavorText: 'Brilha como um arco-íris sob a luz do meio-dia.',
  },
  {
    id: 'salmon',
    name: 'Salmão',
    nameEn: 'Salmon',
    behavior: 'smooth',
    difficulty: 50,
    minSize: 24,
    maxSize: 44,
    basePrice: 75,
    location: 'river',
    color: '#f87171',
    description: 'Nada rio acima para desovar.',
    flavorText: 'Muito apreciado na culinária do Vale do Orvalho.',
  },
  {
    id: 'red_snapper',
    name: 'Cioba',
    nameEn: 'Red Snapper',
    behavior: 'mixed',
    difficulty: 40,
    minSize: 8,
    maxSize: 26,
    basePrice: 50,
    location: 'ocean',
    color: '#ef4444',
    description: 'Um peixe avermelhado muito comum no oceano durante a chuva.',
    flavorText: 'Um peixe de cor vibrante que adora tempestades.',
  },
  {
    id: 'halibut',
    name: 'Alabote',
    nameEn: 'Halibut',
    behavior: 'sinker',
    difficulty: 50,
    minSize: 10,
    maxSize: 33,
    basePrice: 75,
    location: 'ocean',
    color: '#78716c',
    description: 'Um peixe achatado que passa a vida no fundo do mar.',
    flavorText: 'Costuma mergulhar direto para as profundezas.',
  },
  {
    id: 'walleye',
    name: 'Picão-verde',
    nameEn: 'Walleye',
    behavior: 'smooth',
    difficulty: 45,
    minSize: 10,
    maxSize: 30,
    basePrice: 105,
    location: 'lake',
    color: '#a3e635',
    description: 'Um peixe de água doce de olhos grandes que adora dias chuvosos.',
    flavorText: 'Seus olhos reluzem nas profundezas do lago da montanha.',
  },

  // HARD DIFFICULTY
  {
    id: 'pike',
    name: 'Lúcio',
    nameEn: 'Pike',
    behavior: 'dart',
    difficulty: 60,
    minSize: 20,
    maxSize: 45,
    basePrice: 100,
    location: 'river',
    color: '#22c55e',
    description: 'Um predador voraz de água doce que se move em arrancadas rápidas.',
    flavorText: 'Dá solavancos repentinos para escapar da linha.',
  },
  {
    id: 'tuna',
    name: 'Atum',
    nameEn: 'Tuna',
    behavior: 'smooth',
    difficulty: 70,
    minSize: 12,
    maxSize: 60,
    basePrice: 100,
    location: 'ocean',
    color: '#3b82f6',
    description: 'Um peixe oceânico grande e musculoso.',
    flavorText: 'Puxa a vara com força contínua e firmeza.',
  },
  {
    id: 'catfish',
    name: 'Peixe-gato',
    nameEn: 'Catfish',
    behavior: 'sinker',
    difficulty: 75,
    minSize: 12,
    maxSize: 72,
    basePrice: 200,
    location: 'river',
    color: '#374151',
    description: 'Um peixe barbilhudo que nada vigorosamente no leito lamacento do rio.',
    flavorText: 'Mergulha com ferocidade para o fundo da água.',
  },
  {
    id: 'sturgeon',
    name: 'Esturjão',
    nameEn: 'Sturgeon',
    behavior: 'mixed',
    difficulty: 78,
    minSize: 12,
    maxSize: 60,
    basePrice: 200,
    location: 'lake',
    color: '#64748b',
    description: 'Um peixe antigo e valioso. Seus ovos produzem o cobiçado caviar.',
    flavorText: 'Nobre habitante do lago da montanha.',
  },
  {
    id: 'pufferfish',
    name: 'Baiacu',
    nameEn: 'Pufferfish',
    behavior: 'floater',
    difficulty: 80,
    minSize: 1,
    maxSize: 36,
    basePrice: 200,
    location: 'ocean',
    color: '#eab308',
    description: 'Infla seu corpo quando ameaçado. Tende a subir para a superfície.',
    flavorText: 'Flutua repentinamente para o topo da água.',
  },
  {
    id: 'lingcod',
    name: 'Donzela',
    nameEn: 'Lingcod',
    behavior: 'dart',
    difficulty: 85,
    minSize: 30,
    maxSize: 50,
    basePrice: 120,
    location: 'river',
    color: '#0d9488',
    description: 'Um predador voraz que dá arrancadas agressivas.',
    flavorText: 'Muito arisco e imprevisível.',
  },
  {
    id: 'super_cucumber',
    name: 'Superpepino',
    nameEn: 'Super Cucumber',
    behavior: 'sinker',
    difficulty: 80,
    minSize: 12,
    maxSize: 36,
    basePrice: 250,
    location: 'ocean',
    color: '#9333ea',
    description: 'Uma criatura roxa rara e bioluminescente que habita o mar profundo.',
    flavorText: 'Misterioso e pesado, arrasta a linha para baixo.',
  },
  {
    id: 'lava_eel',
    name: 'Enguia de Lava',
    nameEn: 'Lava Eel',
    behavior: 'sinker',
    difficulty: 90,
    minSize: 30,
    maxSize: 35,
    basePrice: 700,
    location: 'lake',
    color: '#dc2626',
    description: 'Uma enguia feroz que sobrevive em lagos de magma incandescente.',
    flavorText: 'Queima as mãos de qualquer pescador despreparado!',
  },
  {
    id: 'octopus',
    name: 'Polvo',
    nameEn: 'Octopus',
    behavior: 'sinker',
    difficulty: 95,
    minSize: 12,
    maxSize: 48,
    basePrice: 150,
    location: 'ocean',
    color: '#0284c7',
    description: 'Criatura marinha lendária por sua inteligência e força surpreendente.',
    flavorText: 'Extremamente difícil de manter na barra verde!',
  },

  // LEGENDARY FISH
  {
    id: 'crimsonfish',
    name: 'Peixe-carmesim',
    nameEn: 'Crimsonfish',
    behavior: 'legendary',
    difficulty: 95,
    minSize: 20,
    maxSize: 21,
    basePrice: 1500,
    location: 'ocean',
    color: '#e11d48',
    isLegendary: true,
    description: 'Vive em cavernas profundas no mar. Suas escamas são de um carmesim vivo.',
    flavorText: 'Um dos lendários soberanos das águas de Pelican Town.',
  },
  {
    id: 'glacierfish',
    name: 'Peixe-gelo',
    nameEn: 'Glacierfish',
    behavior: 'legendary',
    difficulty: 100,
    minSize: 26,
    maxSize: 28,
    basePrice: 1000,
    location: 'river',
    color: '#38bdf8',
    isLegendary: true,
    description: 'Gera gelo ao redor do corpo para repelir qualquer predador.',
    flavorText: 'Dá saltos cortantes e congelantes nas corredeiras.',
  },
  {
    id: 'legend',
    name: 'A Lenda',
    nameEn: 'The Legend',
    behavior: 'legendary',
    difficulty: 110,
    minSize: 49,
    maxSize: 51,
    basePrice: 5000,
    location: 'lake',
    color: '#eab308',
    isLegendary: true,
    description: 'O rei de todos os peixes! Dizem que ninguém consegue pegá-lo sem maestria absoluta.',
    flavorText: 'Coroa de ouro e fúria lendária na água!',
  },
];

export const RODS: Rod[] = [
  {
    id: 'bamboo_pole',
    name: 'Vara de Bambu',
    nameEn: 'Bamboo Pole',
    price: 0,
    levelRequired: 0,
    allowsBait: false,
    allowsTackle: false,
    barSizeBonus: 0,
    description: 'Uma vara de pescar simples e tradicional dada pelo Willy.',
  },
  {
    id: 'fiberglass_rod',
    name: 'Vara de Fibra de Vidro',
    nameEn: 'Fiberglass Rod',
    price: 1800,
    levelRequired: 3,
    allowsBait: true,
    allowsTackle: false,
    barSizeBonus: 8,
    description: 'Feita de fibra de vidro flexível. Permite equipar iscas para acelerar as fisgadas.',
  },
  {
    id: 'iridium_rod',
    name: 'Vara de Irídio',
    nameEn: 'Iridium Rod',
    price: 7500,
    levelRequired: 6,
    allowsBait: true,
    allowsTackle: true,
    barSizeBonus: 18,
    description: 'Forjada com o raro metal de irídio. Permite usar tanto iscas quanto boias e anzóis especiais!',
  },
];

export const TACKLES: Tackle[] = [
  {
    id: 'cork_bobber',
    name: 'Boia de Cortiça',
    nameEn: 'Cork Bobber',
    price: 750,
    description: 'Aumenta ligeiramente o tamanho da barra de pesca verde (+24px).',
    icon: '🪵',
  },
  {
    id: 'trap_bobber',
    name: 'Boia de Armadilha',
    nameEn: 'Trap Bobber',
    price: 500,
    description: 'Faz com que o peixe escape 33% mais devagar quando estiver fora da barra.',
    icon: '🪤',
  },
  {
    id: 'lead_bobber',
    name: 'Boia Pesada de Chumbo',
    nameEn: 'Lead Bobber',
    price: 400,
    description: 'Elimina completamente o rebote quando a barra verde atinge o fundo!',
    icon: '⚓',
  },
  {
    id: 'treasure_hunter',
    name: 'Caçador de Tesouros',
    nameEn: 'Treasure Hunter',
    price: 750,
    description: 'Aumenta a chance de baús de tesouro em 35% e impede que o peixe fuja enquanto coleta.',
    icon: '🪙',
  },
  {
    id: 'barbed_hook',
    name: 'Anzol Farpado',
    nameEn: 'Barbed Hook',
    price: 1000,
    description: 'Ajuda a prender a barra verde diretamente ao peixe com magnetismo suave.',
    icon: '🪝',
  },
];

export const BAITS: Bait[] = [
  {
    id: 'regular_bait',
    name: 'Isca Comum',
    nameEn: 'Bait',
    price: 5,
    description: 'Faz os peixes morderem o anzol 50% mais rápido.',
    icon: '🐛',
  },
  {
    id: 'magnet_bait',
    name: 'Ímã',
    nameEn: 'Magnet',
    price: 15,
    description: 'Aumenta a chance de encontrar baús de tesouro submarinos em +15%.',
    icon: '🧲',
  },
  {
    id: 'wild_bait',
    name: 'Isca Selvagem',
    nameEn: 'Wild Bait',
    price: 25,
    description: 'Receita misteriosa do Linus. Tem chance de fisgar dois peixes de uma vez!',
    icon: '🌿',
  },
];

export const TREASURE_LOOT: TreasureItem[] = [
  { id: 'diamond', name: 'Diamante', value: 750, icon: '💎', rarity: 'rare' },
  { id: 'ruby', name: 'Rubi', value: 250, icon: '♦️', rarity: 'common' },
  { id: 'emerald', name: 'Esmeralda', value: 250, icon: '🟢', rarity: 'common' },
  { id: 'gold_ore', name: 'Minério de Ouro (x5)', value: 150, icon: '🟡', rarity: 'common' },
  { id: 'amethyst', name: 'Ametista', value: 100, icon: '🟣', rarity: 'common' },
  { id: 'prismatic_shard', name: 'Fragmento Prismático', value: 2000, icon: '🌈', rarity: 'ultra-rare' },
  { id: 'ancient_doll', name: 'Boneca Antiga', value: 500, icon: '🎎', rarity: 'rare' },
  { id: 'dino_egg', name: 'Ovo de Dinossauro', value: 1200, icon: '🥚', rarity: 'ultra-rare' },
];

export const LEVEL_XP_THRESHOLDS = [
  0,      // Level 0
  100,    // Level 1
  380,    // Level 2
  770,    // Level 3
  1300,   // Level 4
  2150,   // Level 5
  3300,   // Level 6
  4800,   // Level 7
  6900,   // Level 8
  10000,  // Level 9
  15000,  // Level 10
];
